### ISSUE TITLE
realtime date grid  line bug 

### ISSUE THREAD

**Issue by easylogic** [juijs/jui-chart#10]
리얼타임 그리드를 그릴 때  line : solid 로 옵션을 주면 

첫번째 라인이 계속 사라 지는 현상.

**Comment by seogi1004** [comment]
빨리해줘요오오오~

**Comment by easylogic** [comment]
이거 왜 X  Y 라인 체크 하는 함수가 거꾸로 되어 있나 희한하네 ㅠ

**Comment by seogi1004** [comment]
@easylogic 이거 다시 확인이요.
