### ISSUE TITLE
splitarea차트 target적용시 SVG4601 : SVG경로 데이터의 형식이 잘못되어 구문 분석오류 뜨는 문제

### ISSUE THREAD

**Issue by lover74n** [juijs/jui-chart#102]
splitarea차트에 현재시간을 pin으로 고정하는 차트를 만들고 있는데요
Deberg모드로 보면 
(explorer11 -> SVG4601 : SVG경로 데이터의 형식이 잘못되어 구문 분석오류(warning?) 뜨던데요..
크롬은 invalid value for <path> attribute d="Munderfinded, undefinded" 라고 뜨구요.

소스에 
brush : [{
    type:"splitarea",
    target:["tps"],   <-- 이부분 주석처리하면 위의 오류(warning?)는 뜨지 않더라구요.. 
                                  그래서 이것저것 다 해봐도 안 없어져서요..
    axis:0
},{
    type:"pin",
    axis:0,
    format:function(d){
        return time.format(d, "HH:mm");
    }
}
그래서 참조 소스 찾아보니
http://jui.io/?p=gallery.realtime  여기에 비슷한게 있더라구요 근데 여기에도 똑같은 오류
뜨던데.. 정상적으로 그래프는 그려지는데 오류가 떠 있으니 찝찝해서요..

**Comment by seogi1004** [comment]
확인해보겠습니다. ㅠㅠ
