### ISSUE TITLE
Y축 domain 문의드립니다.

### ISSUE THREAD

**Issue by lagoonKmj** [juijs/jui-chart#104]
현재 문제점 : 
 10초마다 차트를 갱신하는데, svg엘리먼트를 다지우고 chart를 새로 빌드한다.,

그래서 초기에 한번 차트를 그리고 그다음은 데이터 만 바꾸는걸로 수정하였습니다.
데이터는 잘바뀌는데, 문제는 y축의 Max값이 문제더라고요.
방법좀 알려주시면 감사하겠습니다.

//Max Usage 구하기
maxUsage = Math.max.apply(Math,data.map(function(o){return o.used_bytes;}))*1.2;
if(maxUsage == 0){
      maxUsage = 1;
}
//차트생성시 Y축 도메인
, domain: [0,maxUsage]

**Comment by seogi1004** [comment]
http://chartplay.jui.io/?p=grid_set_domain3
