### ISSUE TITLE
숫자포맷관련 showText, display 이슈

### ISSUE THREAD

**Issue by inkyung** [juijs/jui-chart#110]
안녕하세요
showText 또는 display:"all"할때 
y축과 차트 값표현에서 
숫자 첫만단위별로 콤마 찟는 방법은 없나요?

**Comment by inkyung** [comment]
해결 했습니다

**Comment by easylogic** [comment]
숫자에 대한 포맷팅은 따로 제공하고 있지 않습니다.

자유도가 많은 부분이라  하시는 용도에 맞게 format 함수를 재구성 해주시면 됩니다. 

http://chartplay.jui.io/?p=grid_block_format

이쪽 보시면  x 축 text 부분이 format 으로 변환된 것으로 나옵니다. 

참고하세요.

**Comment by inkyung** [comment]
넵 감사합니다 
accounting.js를 사용해서 domain format과 전체 format에 
표현방식을 적용해서 해결했습니다.

1) 도메인
               y : {
	            type : "range",
	             domain : function(data) {
	                return data.samsung+data.lg;
	                },
		     format : function(data) {
			  return accounting.formatNumber(data);
		       },
	           line : true,
	           orient:"left"
	        },
2) 전체
		format: function (data) {
			if (typeof(data) == "number") {
				return accounting.formatNumber(data);
			}
			return data;
		}
