### ISSUE TITLE
IE8버전에서 호출하는 방법 문의드립니다.

### ISSUE THREAD

**Issue by inkyung** [juijs/jui-chart#114]
업무시스템이 IE8~9인데 차트 호출이 안되네요..

공식적으로는 IE9이상만 지원하지만

다른방법으로 IE8에서도 사용가능한 지 문의 드립니다.

**Comment by easylogic** [comment]
안녕하세요. 

현재 IE9 부터 지원하고 있습니다. 

왜냐하면 IE8 이  svg 포맷을 지원하지 않기 때문에  사용을 할 수가 없습니다.
