### ISSUE TITLE
area 차트 데이터 add할때 차트창 깨지는 문제

### ISSUE THREAD

**Issue by lover74n** [juijs/jui-chart#119]
차트 그릴때 초기 10분치 데이터를 가지고 와서 데이터를 넣습니다.. 
이건 정상적으로 그려지는데요..
이후 10초치 데이터를 가지고 와서 add 시키는데요

areaData.shift();

var domain = [new Date(new Date() - time.MINUTE*(10), new Date()];

for(var i=0; i<10; i++){
    var area ={
        t1 : i,
        time : time1[i]//쿼리에서 가지고 온 시간을 getTime()한 값 <-- 이부분에서 잘못된거 같은데요
    }
    areaData.push(area);
}

time부분에 새로 그려져야할 영역 domain[1]를 넣으면 정상적으로 그려지는데
10초치에 제가 원하는 시간에 데이터를 넣고 싶은데 저렇게하면 차트 틀이 깨지더라구요

글의 요점은 차트를 데이터를 add시킬때 한번이 아니라 10초치에 데이터를 여러번 add시키고 싶은데
time부분에 var domain = [new Date(new Date() - time.MINUTE*(10), new Date()];  방법만 가능한가요?
위의 예처럼 사용자 임의의 시간을 넣고 차트 그리는건 안되나요?

**Comment by seogi1004** [comment]
잉 해결 되신건가요?
