### ISSUE TITLE
X-View차트에 타이틀 옆에 체크박스 넣고 싶은데 가능한가요?

### ISSUE THREAD

**Issue by lover74n** [juijs/jui-chart#123]
x-view에
widget : [{
              type : "title"
              text  : "X-view"   <--여기에 html input 테크넣고 싶은데 text로 되어 있어서 태그가 안되더라구요
                                              html로 바꾸면 오류나고.. 혹시 방법없나요?

여기에 넣는 방법이 없으면 absolute로 체크박스 배치해야겠네요?

**Comment by easylogic** [comment]
title 위젯은 svg 안에서 제공되는 것이라  html 을 사용하실 수가 없습니다. 

말씀하신대로 div 형태로 absolute 로 잡으시고 배치하시는게 좋을 것 같아요.
