### ISSUE TITLE
pie 차트에서 activeEvent 이벤트 문의 드립니다

### ISSUE THREAD

**Issue by lover74n** [juijs/jui-chart#124]
pie 차트에서 activeEvent : "click" 이벤트를 추가 했는데요

데이터가 두개 이상일때는 ex) var data = [{ ie:20, ff:10 }] 일때는 클릭하면
정상적으로 벌어지는데.. 한개일때는 var ex) [{ie:20}] 일때는 클릭하면
차트 전체가 아래로 많이 이동하더라구요..

조회한 데이터가 위처럼 1건일시 activeEvent 옵션을 제거 하고 싶은데 방법을 모르겠어서 문의드립니다.
차트 객체가 pieChart 일시

질문 1. pieChart.brush.removeEvent("activeEvent"); 이런식으로 삭제하는 방법이 있나요?

질문 2. 3차원 pie 차트는 없나요?

이슈게시판에 맞는 글인지는 모르겠지만 알려주시면 감사하겠습니다

**Comment by easylogic** [comment]
답변 1.  현재 이벤트를 동적으로 삭제하는 방법은 제공하고 있지 않습니다. 

기능에 대해서는 고민을 좀 해봐야할 것 같습니다.  
만약에 한다면 특정 이벤트가 일어났을 때 현재 상태의 차트를 지우고  activeEvent 설정안한 차트로 바꿔야할 것 같습니다. 

답변 2. 옵션에 `"3d" : true ` 주시면 3d 차트가 나옵니다.  하지만 퀄리티가 좋지 않아 현재는 권장하지 않습니다.

**Comment by lover74n** [comment]
넵 답변 감사합니다!!
