### ISSUE TITLE
세로 막대 그래프(column) Y축 도메인값 변경가능한가요?

### ISSUE THREAD

**Issue by lover74n** [juijs/jui-chart#125]
조회버튼을 누른후 Y축 값 최대값을 구한 뒤 Y축 도메인을 다시 설정하고 싶은데

realtime Line chart에서는 가능하던데 barChart에서는 변경이 안되더라구요

막대에서는 구현이 안되는건가요?

ex) var barChart;

jui.ready(["chart.builder"], function(builder){
    barChart = builder("#barChart",{
      ....생략
    ));
});
조회버튼 클릭후 막대로 보여져야 할 데이터 가지고 와서 가공후
barChart.axis(0).update(barData);
barChart.axis(0).set("Y", { domain : [0, max] } );
barChart.render();  <--이렇게 하니 도메인 값이 변경이 안되더라구요.. 
                                    Realtime Chart는 이런식으로 변경했구요..
                                    막대차트는 변경안되는건지 모르겠네요

**Comment by easylogic** [comment]
아래 와 같은 형태로 바꾸보세요. 

```
   // grid 축 변경하기 
    barChart.axis(0).updateGrid("y", {
        domain : [ 0, max ]
    }, true);

```
자세한 코드는 여기를 참고하시면 됩니다.  

동적으로  축을 바꾸는 예제입니다. 


http://chartplay.jui.io/?p=update_axis_grid

**Comment by lover74n** [comment]
barChart.axis(0).updateGrid("y", {
        domain : [ 0, max ]
    });  <-- true 파라미터 빼니깐 정상적으로 적용되었습니다 감사합니다

혹시 막대그래프 너비 고정할수는 없나요? width=1160에 데이터가 3건이면 막대가 3개 나오는데
1160/3 으로해서 너무 크게 나오더라구요.. 자꾸 질문드려서 죄송합니다

**Comment by seogi1004** [comment]
아래 샘플 참고하시면 됩니다.
http://chartplay.jui.io/?p=fixed_column

**Comment by lover74n** [comment]
넵 감사합니다 수고하세요
