### ISSUE TITLE
domain명이 같은경우 하나만 표시되네요 ㅠ

### ISSUE THREAD

**Issue by parkdonguk** [juijs/jui-chart#143]
![1](https://user-images.githubusercontent.com/17606833/27361855-04ddff6a-5665-11e7-816a-0fff10035bf1.JPG)
![2](https://user-images.githubusercontent.com/17606833/27361856-075f3af6-5665-11e7-996e-bd14accd52bb.JPG)

붉은색 동그라미 보시면 이름이 똑같지만 엄연히 다른 데이터인데..
그래프 표시는 하나로 되더라구요. . 같은 이름에 대해 마지막으로 들어온 데이터만 표시되는거같은데
방법이 없을까요?

**Comment by easylogic** [comment]
흠 이름 기준을 다르게 하셔야 할 것 같은데요 . 

상품명이랑 규격을 모아서 도메인을 구성하셔야 할 것 같습니다.

아니면 규격 기준으로 구분이 가능하신가요?

**Comment by parkdonguk** [comment]
@easylogic 
조합하기에는 도메인명이 너무 길어질거같고.. 저것도 사실 짧은 품목명과 규격들이거든요.
규격도 상품은 다르지만 규격이 같은경우도 생겨서.. 
아무튼 도메인명이 같으면 안된다는 말씀이신거죠~~?
제가 방법을 강구해봐야겠네요 ㅠ_ㅠ

**Comment by easylogic** [comment]
애부적으로 수치계산할때 키 하나만 가지고 계산해서요 . 배열 인덱스로 구분하는 것을 낳어야 할 수도 있겠네요

**Comment by parkdonguk** [comment]
@easylogic 
아하 넵 일단은 앞에 Rank-품목명으로 이름주기로 했네요 ㅎㅎ
