### ISSUE TITLE
안녕하세요 scatter 사용시 질문이 있습니다.

### ISSUE THREAD

**Issue by jonggyun** [juijs/jui-chart#148]
안녕하세요. 

좋은 툴을 이렇게 제공해주셔서 감사합니다. 잘 쓰고 있는 사람 중 한 명입니다.

사용중에 궁금한 점이 있어 이렇게 글을 남기게 되었습니다.

현재 실시간 그래프를 그리는 brush를 line과 scatter 2가지를 이용하고 있는데요.

브라우저의 다른 탭을 이용하다가 실시간 그래프가 있는 탭으로 돌아왔을 경우

아래 사진과 같은 현상이 발생하는 경우가 생기는데, line은 벗어나질 않지만 scatter만 벗어나게 되네요.

![scatter](https://user-images.githubusercontent.com/15382701/29103096-94241a9c-7cf8-11e7-8c28-380402409cc1.png)

실시간 그래프 예제 중에 scatter를 지정해도 그래프 밖으로 벗어나지 않던데,  따로 특별히 설정해야 하는 부분이 있는건지 궁금합니다. 아래 소스는 제 brush 부분입니다.
 
				brush: [{
					type: "line",
					colors: cpuMemoryColor
				}, {
					type: "scatter",
					target: ["Cpu", "Memory"],
					symbol: "circle",
					size: 8,
					colors: cpuMemoryColor
				}],

**Comment by easylogic** [comment]
scatter 차트가  clip  기본 옵션이 false 로 잡혀있네요. 

화면이 넘어갈 경우  `clip: true`  를 옵션으로 주시면 화면 넘어가는 부분은 안 보입니다.

**Comment by jonggyun** [comment]
감사합니다!!
