### ISSUE TITLE
Drawing a brush to canvas

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui-chart#15]
브러쉬 영역만 캔버스로 그려보는건 어떻소?
위젯과 그리드는 그대로 사용하는거요.

**Comment by easylogic** [comment]
캔버스를 svg 랑 겹칠 수 잇는지 먼저 해보고 

내 생각에는 svg 위에 canvas  를 올리면 좋지 않을까 하오.. 

그 전에 canvas쪽  라이브러리도 만들어야할 것 같은데.

잘 구상을 한번 해보시요

**Comment by easylogic** [comment]
```javascript

// svg 가 이런 식이라면 
this.svg.rect( .... );

// canvas 도 이런식이 되면 좋을 듯 하오 
this.canvas.rect( ...  );

```

비슷한 형태로만 갈 수 있으면 좋겠지만 아니라도 상관 없으니 한번 해보시오.

**Comment by seogi1004** [comment]
@easylogic 저건 사용 패턴이 아니라 개발 패턴이라서...

어차피 드로잉 api는 브러쉬마다 다르게 쓰는 것이기 때문에 굳이 인터페이스를 맞출 필요가 없어...
저거 맞추기 위해 들어가는 노력으로 캔버스 api를 익히는게 나음...

여튼 polygon 기반의 브러쉬도 구현할 수 있게 만들어놨음...
빌더랑 캔버스 브러쉬 코드보면 정말 몇줄 안됨...

https://github.com/juijs/jui-chart/blob/feature/canvas/sample/canvas/scatter.html

**Comment by seogi1004** [comment]
@easylogic 남은 이슈는 인터랙션에 관련된 건데...

canvas 태그가 위에 올라가는 형태라 canvas 태그로 오는 이벤트를 모두 svg로 넘겨줄 수 있다면 기존의 스카터 드래그 위젯 같은건 그대로 사용할 수 있을듯...

그리고 위에 올려둔 캔버스 스카터 브러쉬 참고해서 메시그리드 캔버스용으로 만들어봐...
성능 테스트 좀 해봅세!
