### ISSUE TITLE
line chart 데이터 값이 모두 0일 때 error

### ISSUE THREAD

**Issue by ivvve** [juijs/jui-chart#192]
안녕하세요 chart로 작업 중인데 오류가 발생해서 질문드립니다.

Line Chart에 Basic Line(http://chartplay.jui.io/?p=line) 에서 모든 데이터를 아래와 같이 모두 0으로 줄 경우 오류가 발생하는데 다른 설정이 필요한 것인가요??
```
data : [
            { apple : 0, microsoft : 0, oracle : 0},
            { apple : 0, microsoft : 0, oracle : 0},
            { apple : 0, microsoft : 0, oracle : 0},
            { apple : 0, microsoft : 0, oracle : 0}
        ]
```

**Comment by seogi1004** [comment]
@ivvve y축 domain값이 데이터 기반이라 발생하는 문제에요.
[0,1] 이런식으로 넣으면 라인이 그려집니다 ㅠ

**Comment by ivvve** [comment]
y축 domain이 0이라 생긴 문제였군요 
말씀하신대로 
return Math.max(d.apple, d.microsoft, d.oracle); 를
return [Math.max(d.apple, d.microsoft, d.oracle), 1]; 로 변경하니까 해결됐습니다. 👍

감사합니다.
close 하도록 하겠습니다
