### ISSUE TITLE
Legend on set brush config

### ISSUE THREAD

**Issue by irawan2018** [juijs/jui-chart#194]
I have 2 chart (multi axis). I want set legend separately group by brush of chart:
`{
                  type : "legend",
                  orient : "left",
                  filter : true,
                  brush : 0
                }
                ,{
                  type : "legend",
                  orient : "right",
                  filter : true,
                  brush : 1
                }`
It's look bug: 'length' of undefined.

**Comment by seogi1004** [comment]
2.5.6 version check please.
Fixed a bug that caused script errors when using multiple legends.

**Comment by seogi1004** [comment]
Please check the example page.
https://github.com/juijs/jui-chart/blob/master/examples/multi_axis_with_zoom_for_date.html
