### ISSUE TITLE
Zoom function on multi-axis 

### ISSUE THREAD

**Issue by irawan2018** [juijs/jui-chart#195]
I create 2 variables line chart (multi axis), so for zoom function i set to both axis. 
`axis: [0,1]`
When drag and zoom, both line moving together. But when close/reset zoom, it need to click one by one (close every axis/variable line chart). I need one close for both of zoom line chart.

**Comment by seogi1004** [comment]
I added the itegrate option of the zoom widget to version 2.5.3.
A sample is shown below.

https://github.com/juijs/jui-chart/blob/master/examples/multi_axis_with_zoom.html

**Comment by irawan2018** [comment]
it can run for x-domain type as 'block'. But for type as 'date', when the zoom is closed, the chart isn't updated to default value (previous view).

**Comment by seogi1004** [comment]
Fixed a bug where rollback did not work when the x-axis was in date format in the Zoom widget.
2.5.4 version check please.

**Comment by seogi1004** [comment]
2.5.5 version check please~

**Comment by irawan2018** [comment]
When i zoom twice then i close, it's not return to the first interval/format.
Example: default x interval is 10 hours. I zoom to 1 hour interval, then i zoom again to 10 minutes interval. When i close, it's return to 1 hour interval, it's not return to 10 hours interval.
On previous version is back to the first interval (10 hours interval).

**Comment by seogi1004** [comment]
2.5.6 version check please.
Fixed a change to the initial state when restoring a zoom from a zoom widget.

**Comment by irawan2018** [comment]
It's work, thanks.
