### ISSUE TITLE
Scatter - line chart brush on filter legend

### ISSUE THREAD

**Issue by irawan2018** [juijs/jui-chart#200]
I added brush scatter on line chart
`brush : [
            { type : "line", target : "sales", axis : 0, colors : [ "#434348" ] , symbol : "curve" },
            { type : "line", target : "profit", axis : 1, colors: [ "#90ed7d" ], symbol : "curve" },
            { type : "scatter", axis : 0, target : "sales", colors : [ "#434348" ], clip: true },
            { type : "scatter", axis : 1, target : "profit", colors: [ "#90ed7d" ], clip: true }
]`
When activate filter of legend, it's work separately. How to set legend filter on both? 
`{ type : "legend", brush : [ 0,2 ], align : "start", filter : true }`
<img width="356" alt="image" src="https://user-images.githubusercontent.com/45579586/51788557-d2bc6200-21b1-11e9-8a62-9efbd4a97b24.png">

**Comment by seogi1004** [comment]
Use the 'brushSync' option.

```js
widget : [
        { type : "title", text : "Combination Sample" },
        { type : "legend", brush : [ 0, 1 ], align : "start", filter : true, brushSync: true },
        { type : "legend", brush : [ 2 ], align : "end", filter : true },
        { type : "zoom", axis : [ 0, 1 ], integrate : true }
    ]
```
