### ISSUE TITLE
Tooltip on zoom function

### ISSUE THREAD

**Issue by irawan2018** [juijs/jui-chart#201]
I set tooltip on the scatter brush. 
When zoom, it's not show, like closed by backdrop of zoom.

**Comment by seogi1004** [comment]
Unfortunately, tooltips are not available at zoom.
This is because the zoom layer blocks the event.
Instead, use the line brush's display option.

**Comment by irawan2018** [comment]
It's work for 2.5.7 version after removed background on zoom.
Thanks.
