### ISSUE TITLE
To improve the topology brush

### ISSUE THREAD

**Issue by egaoneko** [juijs/jui-chart#37]
노드 생성시에 node와 edge에 대한 size를 설정할 수 있으면 합니다~

**Comment by egaoneko** [comment]
http://visjs.org/examples/network/data/scalingCustom.html

**Comment by seogi1004** [comment]
chart가 아닌 axis 기반으로 변경하기

**Comment by seogi1004** [comment]
axis 기반으로는 변경 완료

**Comment by seogi1004** [comment]
줌과 위치 변경 기능은 내부적으로 구현하였음

**Comment by seogi1004** [comment]
1. 토폴로지 배치 로직 별도 모듈로 분리하는 구조로 변경
2. 토폴로지 원형 배치 구현
