### ISSUE TITLE
Changed references after the 'scale' function call

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui-chart#49]
block 도메인이 [ "Q1", "Q2", "Q3", "Q4" ]가 있음

var domains = this.axis.x.domain();
위에 리스트가 나옴.

하지만 아래 코드 실행 후...
this.axis.x(0)

[ 0, "Q2", "Q3", "Q4" ]로 참조가 변경됨

**Comment by easylogic** [comment]
샘플 페이지 주세요 ~

**Comment by easylogic** [comment]
그리고 다른데는 확인 안해도 됩니다.  

블럭만 셋팅하는게 있기 때문에. 

그런데 range 가 설정 안된 상태에서만 셋팅하는데 이상하네 ㅡㅡ;

**Comment by easylogic** [comment]
이건 d3 따라할려고 만든 기능이라.. 일단은 빼겠음.. 

지금 당장 우리가 쓰지는 않는 것 같으니....

**Comment by easylogic** [comment]
적용.
