### ISSUE TITLE
To improve the topology brush

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui-chart#55]
- [x] 배치 알고리즘 별도의 모듈로 분리
 - [ ] 원형 배치 알고리즘 추가
 - [x] 노드 크기 콜백 옵션 추가
 - [x] 엣지 투명도 콜백 옵션 추가
 - [x] 노드 클릭시, 연결된 간선 활성화 기능 추가 (activeNode 같은 옵션도 필요할지도)

**Comment by egaoneko** [comment]
해당 Issue에 대한 json 파일입니다.

[issue_json.zip](https://github.com/juijs/jui-chart/files/163480/issue_json.zip)

**Comment by easylogic** [comment]
:+1:

**Comment by seogi1004** [comment]
http://bl.ocks.org/mbostock/1153292
