### ISSUE TITLE
Fail to sync color between legend widget and color of brush

### ISSUE THREAD

**Issue by dovewing** [juijs/jui-chart#59]
1.Brush의 colors 옵션에 function()을 사용하여 설정 한 뒤 legend widget을 사용할 경우 colors 옵션이 widget과 sync되지 않는다.
2.1과 동일한 케이스에 legend widget의 filter:true 추가한 뒤 switch 작동시 Brush의 colors가 default가 된다.

**Comment by seogi1004** [comment]
legend 위젯의 colors 옵션을 만들었습니다.
colors 콜백은 target이 아닌 data를 기준으로 구성하는 것이라 완벽하게 싱크를 맞추기가 어렵네요.
일단 colors 옵션에 색상을 똑같이 맞춰주세요.
