### ISSUE TITLE
Title widget rendered in weird position

### ISSUE THREAD

**Issue by incleaf** [juijs/jui-chart#63]
<img width="520" alt="screen shot 2016-03-22 at 10 46 14 pm" src="https://cloud.githubusercontent.com/assets/7221609/13953576/f470a4f8-f07f-11e5-8740-0b962246a3ea.png">
<img width="525" alt="screen shot 2016-03-22 at 10 46 29 pm" src="https://cloud.githubusercontent.com/assets/7221609/13953577/f4784d7a-f07f-11e5-9ec7-b0aa0ba2c66b.png">

- 첫번 째 이미지
```javascript
{
  type : "title",
  text : "aaaaaaaaaaaaa",
  align : "start",
  orient : "center",
  dx : -75
 }
```

- 두번 째 이미지
```javascript
{
  type : "title",
  text : "aaaaaaaaaaaaabbbbbbb",
  align : "start",
  orient : "center",
  dx : -75
 }
```
텍스트 수에 따라 좌측 여백이 결정되어서, 텍스트가 길거나, 짧으면 제대로 표시가 되지 않습니다.

**Comment by incleaf** [comment]
dx값 조절하면 되는거였군요 ㅠㅠ

**Comment by seogi1004** [comment]
맞아요! dx, dy로 세부 조절할 수 있어요.
