### ISSUE TITLE
JUI chart 관련..

### ISSUE THREAD

**Issue by ohHyunJae** [juijs/jui-chart#67]
안녕하세요 

JUI chart를 사용하여 그래프를 그리고 있습니다.

제가 처음 chart를 그릴땐 x축엔 0 ~ 900값을 넣었습니다.

 var xDomain = [];

  for (i = 50; i <= 900; i += 50) {
        xDomain  = i;
   }
 	axis: {
		x: {
                type: "fullblock",
                domain:xDomain ,
		line: true
		},
.... 
이런식으로 넣어두고 

interval을 돌려서 y축 데이터를 업데이트 하고 있으며..
x축에 해당되는 값이 900이거나 초과한다면
0부터 다시 그래프를 그리는 식으로 진행중입니다.

그런데. 처음 그래프를 그렸을 때 읽어온 x축의 값이 500이라면 
0~900은 그대로 두고 500부터 그리고 싶은데 혹시 그럴수가있나요..?

지금은 처음 읽어온 x축의 값이 500이라면 500 ~ 900까지 그리는 식으로 하다가 
값이 900이거나 초과한다면 0 ~ 900 그래프를 다시 그리는 식으로 하고 있는데..

혹시 가능한지 해서 질문 남깁니다..

참고로 그래프 설정은... 아래와 같은 설정입니다.
 brush: [{
                    type: "line",
                    animate: true
                }, {
                    type: "scatter",
                    hide: true
                }],
                widget: [
                    { type: "title", text: "" },
                    { type: "legend" },
                    { type: "tooltip", brush: 1 }
                ]

**Comment by seogi1004** [comment]
axis 객체에 updateGrid 메소드를 활용하시면 됩니다.
http://jui.io/play/chart/#update_axis_grid.js

**Comment by easylogic** [comment]
#71 여기 이슈랑 같은거라  일단 닫겠습니다.
