### ISSUE TITLE
Topology 관련

### ISSUE THREAD

**Issue by lordreign** [juijs/jui-chart#68]
안녕하세요 Topology 관련해서 구현해보다가 궁금한사항이있어서 이렇게 글을 남깁니다.
혹시 Topology 에서 각 Node들의 위치를 고정시키는 방법이 있는지 궁금합니다.
예를 들어, x축,y축에 대한 값을 입력하면 그 위치에 고정되는 것처럼 말입니다.
그리고 있다면 어떤 방식으로 하면 될까요?
감사합니다.

**Comment by seogi1004** [comment]
@lordreign 답변이 늦어 죄송합니다.
일단 토폴로지는 노드의 커스텀 배치를 위해 별도로 모듈을 만들어야 합니다.

```
 jui.define("topology.custom.sort", [], function() {
        return function(data, area, space) {
            console.log(arguments);
            var xy = [
                { x: 100, y: 200 },
                { x: 300, y: 200 },
                { x: 500, y: 200 },
                { x: 700, y: 200 },
                { x: 900, y: 200 }
            ];
            return xy;
        }
    });
```

해당 모듈의 함수에는 데이터와 영역, 노드 크기에 대한 값이 넘어갑니다.
커스터마이징할 경우 참고하시면 됩니다.
이렇게 만들어진 모듈을 topologytable 그리드의 sort 옵션에 모듈명을 설정하시면 적용이 됩니다.

```
axis: [{
                c: {
                    type: "topologytable",
                    sort: "topology.custom.sort"
                },
                data: data
            }],
```

관련해서 샘플을 develop 브랜치에 추가해놨으니 참고해주세요.
https://github.com/juijs/jui-chart/blob/develop/sample/topology_custom.html

**Comment by lovedad1984** [comment]
샘플 url 이 안열리네요. 
조금 더 자세한 설명 부탁드려도 될까요?

**Comment by seogi1004** [comment]
@lovedad1984
https://github.com/juijs/jui-chart/blob/legacy/sample/topology_custom.html
브랜치 명이 바뀌었습니다.
es6를 지원하면서 코드를 정리하고 있습니다.
