### ISSUE TITLE
Automatically continuous line in line chart

### ISSUE THREAD

**Issue by Orvacko** [juijs/jui-chart#69]
Is there any option to end line when value is undefined? Ex: when one line is shorter than second (when comparing year with plan)

Example:
- when i remove "sales" from third, line will not show
- when i set it to 0, it will break line down to 0
```
data : [
            { date : new Date("2015/01/01 00:00:00"), sales : 50, profit : 35 },
            { date : new Date("2015/01/01 06:00:00"), sales : 20, profit : 30 },
            { date : new Date("2015/01/01 12:00:00"), sales : 0, profit : 5 },
            { date : new Date("2015/01/01 18:00:00"), sales : 0, profit : 25 },
            { date : new Date("2015/01/02 00:00:00"), sales : 0, profit : 20 }
        ]
```

Is there any solution for example to set as undefined and chart will dont error? (cant set as 0 because it will go down on axis)
```
data : [
            { date : new Date("2015/01/01 00:00:00"), sales : 50, profit : 35 },
            { date : new Date("2015/01/01 06:00:00"), sales : 20, profit : 30 },
            { date : new Date("2015/01/01 12:00:00"), sales: undefined, profit : 5 },
            { date : new Date("2015/01/01 18:00:00"), sales : undefined, profit : 25 },
            { date : new Date("2015/01/02 00:00:00"), sales : undefined, profit : 20 }
        ]
```

So the output effect will not be:

![image](https://cloud.githubusercontent.com/assets/1727586/14200804/c7a7120c-f7ed-11e5-8a1e-db9a031a4fed.png)
- 'undefined' value will be not shown in chart

**Comment by seogi1004** [comment]
I'll answer later review.
Please wait.

**Comment by Orvacko** [comment]
Thx, i paste here you example from frontend (using chart.js).

![image](https://cloud.githubusercontent.com/assets/1727586/14205466/9f1f2c02-f80b-11e5-8c40-d4ea23eb5b31.png)
- red line have data only to 29.01 but blue and green is future plans that have data

My target is to allow this in your jui charts.

**Comment by seogi1004** [comment]
I understand your requirements.
I will add that feature to the brush line as soon as possible.
Thank you good feedback.

**Comment by Orvacko** [comment]
Thank you very much.

**Comment by seogi1004** [comment]
@Orvacko 

There are many ways. But to know the data.
When using two colors in one line, how does this data structure?

**Comment by seogi1004** [comment]
Using the colors option, it may change the color of lines and areas.
The second parameter in the callback function is a data index.

Since the release before you check out the develop branch.
Below are sample links.

http://chartplay.jui.io/?p=split_line_advanced
http://chartplay.jui.io/?p=split_area_advanced

**Comment by Orvacko** [comment]
Thx for reply, but we have little miss understanding. I dont want to have many colors on same line. I have different 2 lines, but one line is shorter with data undefined. But yor code throws error on undefined.
- example input
```
colours: [
    '#f00000', '#0000FF', '#932693', '#18861A'
]

 data: [
      // actual year data, I HAVE only data to actual month, RED LINE, not equal size of data array throws error
     [1, 2, 3, 4, 5],
     // previous year data, I HAVE data for all previoues year, PURPLE LINE
     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    // this can bee green line, undefined throws error
   [undefined, undefined, undefined, undefined, undefined, 6, 7, 8, 9, 10, 11, 12],
    // this can be blue line
 [2, 3, 3, 4, 5, 6, 7, 7, 8, 9, 9, 10]
]

```
- output
![image](https://cloud.githubusercontent.com/assets/1727586/14239604/abbd40f0-fa3d-11e5-9a2e-c39ceea1a6fd.png)

**Comment by seogi1004** [comment]
I understand. Please wait. 
We will resolve within a few days.

**Comment by seogi1004** [comment]
@Orvacko Please check the sample below.
https://github.com/juijs/jui-chart/blob/develop/sample/continuous_line.html

**Comment by Orvacko** [comment]
I think it has good structure and 'null' is good way. Good example.

**Comment by Orvacko** [comment]
I tryed it in your editor:

![image](https://cloud.githubusercontent.com/assets/1727586/14278959/a838ae40-fb2a-11e5-8c62-1503f258ddd9.png)

I think reuslt is good. If you will merge it, it will also be in nodes.js package ?

**Comment by seogi1004** [comment]
When the official release, node.js is also applied in the same way.

**Comment by Orvacko** [comment]
Thank you. Pls, do you know when you will do release? Because wee need it in our company project, so, i have to know some deployment date. Thank you :)

**Comment by seogi1004** [comment]
Sorry for the late reply.
It is expected to release in early May.
