### ISSUE TITLE
라인차트 관련 문의

### ISSUE THREAD

**Issue by ahnjunwoo** [juijs/jui-chart#70]
http://chartplay.jui.io/?p=line 라인차트 툴팁 시 
data : [
{ apple : 26.1, microsoft : 24.86, oracle : 0 },
{ apple : 43.83, microsoft : 25.14, oracle : 0 },
{ apple : 55.03, microsoft : 24, oracle : 0 },
{ apple : 72.95, microsoft : 25.39, oracle : 0 }
]
1.oracle 값을 0으로 설정 시 microsoft : 24.86 라인에 마우스 오버시 툴팁 24.86이 정상적으로 발생되고 oracle 라인에 마우스 오버시 0값이 아닌 microsoft 라인의 값인 24.86이 툴팁에 나옵니다. (설명이 잘되었나..)
2.filter : true 레전드에 필터시 색깔이 자기 마음되로 변경되고 모두 0인값(oracle) filter 제거하여도 보여지네요
```javascript
var chart = jui.include("chart.builder");
chart("‪#‎result‬", {
axis : {
x : {
type : "fullblock",
domain : [ "2010", "2011", "2012", "2013" ],
line : true
},
y : {
type : "range",
domain : function(d) {
return Math.max(d.apple, d.microsoft, d.oracle);
},
step : 10
},
data : [
{ apple : 26.1, microsoft : 24.86, oracle : 0 },
{ apple : 43.83, microsoft : 25.14, oracle : 0 },
{ apple : 55.03, microsoft : 24, oracle : 0 },
{ apple : 72.95, microsoft : 25.39, oracle : 0 }
]
},
brush : [{
type : "line",
animate : true
}, {
type : "scatter",
hide : true
}],
widget : [
{ type : "title", text : "Line Sample" },
{ type : "legend" ,filter : true},
{ type : "tooltip", brush : 1 , }
]
});
```

**Comment by ahnjunwoo** [comment]
![k-001](https://cloud.githubusercontent.com/assets/5328073/14302348/d8d6ce3c-fbda-11e5-81e4-4066b0924c29.jpg)

**Comment by ahnjunwoo** [comment]
![k-002](https://cloud.githubusercontent.com/assets/5328073/14302357/e763ec5a-fbda-11e5-9af2-a74ce3f9d7e2.jpg)
![k-003](https://cloud.githubusercontent.com/assets/5328073/14302360/e9f8574e-fbda-11e5-9e82-f56a5aca8fab.jpg)
![k-005](https://cloud.githubusercontent.com/assets/5328073/14302376/0bff7dc2-fbdb-11e5-9e30-b48dbfe7a51a.jpg)

**Comment by seogi1004** [comment]
@ahnjunwoo 친절하게 스샷까지!
금일 확인해서 알려드리겠습니다! ㅎㅎ

**Comment by ahnjunwoo** [comment]
oracle 값이 0이여도 그래프에 표시가 되요ㅠ

**Comment by seogi1004** [comment]
@ahnjunwoo 문제의 원인이 파악되었습니다.
수정되면 알려드릴게요. ㅋㅋ

**Comment by seogi1004** [comment]
@ahnjunwoo 답변이 늦어서 죄송합니다. develop 브랜치 체크아웃 받으시면 됩니다!
