### ISSUE TITLE
Line chart  관련 질문

### ISSUE THREAD

**Issue by ohHyunJae** [juijs/jui-chart#71]
안녕하세요.

JUI를 잘쓰고 다른 사람들한테도 추천을 간간히 하고 있는 개발자입니다...

얼마전에 질문드렸는데.. 조금 이해가 안되서  다시 질문드립니다.

![image](https://cloud.githubusercontent.com/assets/18163630/14347391/e21b893e-fcf1-11e5-83c8-5e9b2b33c623.png)

위 그래프는 X축이 시간이고 Y축은 value를 갖는 그래프이며
15분마다 다시 그리는 그래프 입니다. 
( 0 ~ 900 ) 

근데 문제점은 일정하지 않게 무작위하게 서버에서 데이터를 가져와 뿌리기 때문에 그 지난 시간만큼 X축으로 이동을 해야하는데 단순 update만 하면 1씩 이동하기때문에 문제가 생김니다...

X축이 보여주는 화면은 저렇게 고정시켜두고 X축을 값에 따라 그래프가 그만큼 이동하는 형식으로 만들 순 없는지요..?

예를들어 X축데이터는 0이였다가 다음 서버에서 데이터를 가져왔을 때
5초후에 데이터를 가져왔다고 치면 X축데이터는 5이므로 5칸을 이동시켜야 하는데 
update를 하면 1칸뿐이 이동을 안하니 문제... 

전에 updateGrid를 말씀하셨는데 updateGrid로 X축 보이는 화면을 저렇게 내비둔 상태로 5칸을 이동을 어떻게시키면되나요...?

바쁘신데 계속 물어봐서 죄송합니다!

**Comment by easylogic** [comment]
@ohHyunJae  안녕하세요.  

혹시 chart 만드신 샘플 코드를 좀 볼 수 있을까요? 

builder 에서 어떤식으로 구성하셨는지 궁금하네요. 

0 ~ 900 까지의  숫자로 x 축이 고정일때 

데이타를 구성하실 때  x 축에 대한  필드가 있다면 

지난 시간만큼 그 필드를 더해주시면 될 듯 한데요. 

자세한건  코드를 어떤식으로 나열하셨는지를 좀 봐야할 것 같습니다.

**Comment by ohHyunJae** [comment]
저도 또한 지난 시간만큼 계산을해서 넣었는데.. 
만약
처음 서버에서 가져온 값  X축 : 0 Y축 : 100,  다음 서버에서 가져온 값 X축 3 Y축 180,
이면 X축 1,2 에대한 Y축값은 알길이 없으니 180-100을해서 그 두개값을 갭을 또 %나눠서 구하고 있긴한데.. 이게  무작위하다보니.. 그에따른 알고리즘을 적용해야 할거 같긴한데 혹시나 JUI에 구현해 놓은 기능이 있나 싶어서 물어봅니다..

풀소스는 아니고 기존소스를 조금 수정해서 ..오타가 좀 있을수 있지만 올립니다..

**Comment by ohHyunJae** [comment]
//처음에는 기본값으로 셋팅
var juiChartInclude = jui.include("chart.builder");

var realTimeResponseTimeCheck = 0;

var lineChartDataList = [{
	value1 : 0, value2: 0, value3: 0, value4: 0
}];

var lineChartXDomain = [];

 //Line chart
for (i = 50; i <= 900; i += 50) {
	lineChartXDomain[i] = i;
}

lineChart = juiChartInclude("#lineChart", {

        axis: {
            x: {
                type: "fullblock",
                domain: lineChartXDomain,
                line: true
            },
            y: {
                type: "range",
                domain: function (d) {
			return Math.max(d.value1, d.value2, d.value3, d.value4) + 100;
                },
                step: 10,
                line: true
            },
            data: lineChartDataList
        },
        brush: [{
            type: "line",
            animate: true
        }, {
            type: "scatter",
            hide: true
        }],
        widget: [
            { type: "title", text: "" },
            { type: "legend" },
            { type: "tooltip", brush: 1 }
        ]

    });

**Comment by ohHyunJae** [comment]
두번째 서버에서 데이터를 가져왔을때 소스
//서버에서 데이터를 가져오면 
(지금은 현재 3초마다 가져오는걸로 해서 3초마다로 계산을 해둠.. 변경을 해야함... 왜냐면 서버에서는 응답을 무작위하게 내려주는 경우도 발생하기에 1~7초)				
var lineChartXDomain;
var lineChartDataListLength = 0;


$.each(rsList.resCommVOList, function (index, element) {

            value1 = element['value1'];
            value2 = element['value2'];
            value3 = element['value3'];
            value4 = element['value4'];
            xTime = element['xTime'] * 1; //xTime값은 0~900값만 들어옴


	    /*
	     *  xTime 가끔 900보다 크게 뻥튀기해서 들어와서 처리하기 위해
	     *  처음 서버에서 데이터를 가져왔을땐 X축을 처음 가져온 위치서부터 시작한다.  또는 XTime값이 900이 넘으면 다시 0부터 그린다. 
	     */
            if (realTimeResponseTimeCheck > xTime && xTime <= 900) { 

                lineChartXDomain = [];
                lineChartDataList = [];

                lineChartDataListLength = lineChartDataList.length;

                var xTimeGap = 50 - (xTime % 50);
                var xTimeGapLength = 900 - xTime;

                // X축 값 셋팅
                for (i=0; i <= xTimeGapLength; i++) {
                    if (i == 0) {
                        lineChartXDomain[i] = xTime;
                    } else if (i == xTimeGap) {
                        lineChartXDomain[i] = xTime + xTimeGap;
                        xTimeGap += 50;
                    } else {
                        lineChartXDomain[i] = "";
                    }
                }

                lineChart.axis(0).updateGrid("x", {
                    domain: lineChartXDomain
                });
                
                lineChartDataList[lineChartDataListLength] =
                    {
                        value1: value1, value2: value2,
                        value3: value3, value4: value4
                    }
		

		/**
		 *  처음 서버에서 데이터를 가져왔을때가 아닐때 
		 *  3초를 계산해서 하고 있습니다... 현재는..
		 */
            } else { 

                lineChartDataListLength = lineChartDataList.length;

                /**
                  * 3초씩 돌리므로 3칸씩 이동하기 위해 시리얼통신으로 가져온 값과 이전 값의 갭을 계산해서 뿌려줍니다.
                 **/
                var beForeValue1 = lineChartDataList[lineChartDataListLength - 1].value1;
                var beForeValue2 = lineChartDataList[lineChartDataListLength - 1].value2;
                var beForeValue3 = lineChartDataList[lineChartDataListLength - 1].value3;
                var beForeValue4 = lineChartDataList[lineChartDataListLength - 1].value4;

                var value1Gap = beForeValue1 - value1;
                var value2Gap = beForeValue2 - value2;
                var value3Gap = beForeValue3 - value3;
                var value4Gap = beForeValue4 - value4;

                lineChartDataList[lineChartDataListLength] = {
                    value1: (value1 + (value1Gap / 100 * 40)).toFixed(2), value2: (value2 + (value2Gap / 100 * 40)).toFixed(2),
                    value3: (value3 + (value3Gap / 100 * 40)).toFixed(2), value4: (value4 + (value4Gap / 100 * 40)).toFixed(2)
                };
                ++lineChartDataListLength;

                lineChartDataList[lineChartDataListLength] = {
                    value1: (value1 + (value1Gap / 100 * 20)).toFixed(2), value2: (value2 + (value2Gap / 100 * 20)).toFixed(2),
                    value3: (value3 + (value3Gap / 100 * 20)).toFixed(2), value4: (value4 + (value4Gap / 100 * 20)).toFixed(2)
                };
                ++lineChartDataListLength;

                lineChartDataList[lineChartDataListLength] = {
                    value1: value1, value2: value2,
                    value3: value3, value4: value4
                };
            }


            if (xTime <= 900) {
                realTimeResponseTimeCheck = xTime;
            } else {
                realTimeResponseTimeCheck += 3;
            }

            lineChart.axis(0).update(lineChartDataList);

        });

**Comment by ohHyunJae** [comment]
X축에 없는시간 동안 값을 찍어놔야 그래프가 자연스럽게 올라가기에.. 위처럼 계산했는데..  알고리즘을 하나 만들어서 1~7초때 유연하게 그릴수 있게하면되지만.. 혹시 JUI에서 자체적으로 기능이있나 싶어서 남겨요 신경써주셔서 감사합니다.

**Comment by easylogic** [comment]
잘 하신거 같아요.. JUI 에서는 아직 저런패턴의 자료형은 지원하지 않습니다. 단순히 나열만지원하는지라. 

#69 

이번에 업데이트 될 것 중에  끊겨진 line 브러쉬를 사용하실 수 있어요. 

끊어진 영역에 대해서 데이타를 null 로 채워넣으면 될 것 같은데 좀 애매하긴 하네요. ^^;;;

**Comment by ohHyunJae** [comment]
알겠습니다 ㅎ 답변감사합니다~
