### ISSUE TITLE
액티브 라인 차트

### ISSUE THREAD

**Issue by Minhwanki** [juijs/jui-chart#74]
몇일전 FaceBook에서 문의 드렸던 내용인데요.
Jui 사이트 샘플중 액티브 라인 차트를 참고하여 cross 위젯을 구현중입니다. 허나 샘플에서 서로 다른 라인들의 영역이 중첩될 때, 중첩되는 영역중 빈 공간을 클릭하는 경우도 라인이 액티브가 되더라고요. 이 부분에 대해서 확인해 주시면 감사 드리겠습니다.

http://chartplay.jui.io/?p=active_line

**Comment by seogi1004** [comment]
develop 브랜치에 반영되었습니다!
