### ISSUE TITLE
pos.y[i] 값 isNaN 처리 해야할 듯 싶습니다. 버그인것 같아요.

### ISSUE THREAD

**Issue by JangCool** [juijs/jui-chart#94]
안녕하세요. 버그가 있는 것 같습니다. 제가 현 상황이 재현까지는 좀... 어렵구요.
jui에서 NaN을 발생하는 경우가 있습니다.
디버거로 쫓아 가봤더니 chart.js의 11000 라인 이후 소스 에서 확인이 가능 하더라구요.

        this.createTooltip = function(g, pos, index) {
            var display = this.brush.display;

            for (var i = 0; i < pos.x.length; i++) {
                if((display == "max" && pos.max[i]) || (display == "min" && pos.min[i]) || display == "all") {
                    var orient = (display == "max" && pos.max[i]) ? "top" : "bottom";

                    var minmax = this.drawTooltip(this.color(index), circleColor, 1);
                    minmax.control(orient, pos.x[i], pos.y[i], this.format(pos.value[i]));

                    g.append(minmax.tooltip);

                    // 컬럼 상태 설정 (툴팁)
                    this.lineList[index].tooltip = minmax;
                }
            }
        }

이소스 인데 pos.y[i] 값이 NaN으로 떨어지는 경우가 있는것 같습니다. 
현재 차트에 이런 에러들이 나긴하지만 차트가 문제있거나 그런점은 없구요..
NaN일 경우 뭔가 처리를 해주셔야 할 것 같습니다. 확인 좀 부탁 드려요.

core.js:4112 Error: <g> attribute transform: Trailing garbage, "….00673359374997,NaN)".
core.js:4112 Error: <path> attribute d: Expected number, "…418.11424671875,NaN L421.0779153…".

**Comment by easylogic** [comment]
리포팅 감사합니다. 

혹시 data 어떤식으로 구성하셨는지 알 수 있을까요?

**Comment by easylogic** [comment]
적용되었습니다.
