### ISSUE TITLE
Realtime Chart에서 사용 가능한 저장소 부족으로 인한 error 해결방법?

### ISSUE THREAD

**Issue by lover74n** [juijs/jui-chart#95]
Realtime Chart ->  Transaction View

예제에 있는 Transaction View를 이용해서 차트를 만들었는데요..
20분정도 경과가 하면 

setInterval(function() {
    var domain = getDomain();

    appendTxData(txData, domain);
    chart.axis(0).update(txData);
    chart.axis(0).updateGrid("x", { domain : domain });
    chart.render();  <-- _**사용가능한 저장소가 부족하여 이 작업을 마칠 수 없습니다**_ <-- 오류
}, 1000);

인터넷 안되는 환경에 제이쿼리 버전은 jquery-2.1.4.min.js  Realtime적용 시간은 1시간입니다.
Realtime차트 데이터가 메모리에 계속 누적되어 장시간 사용시 메모리부족 문제 등 
브라우저(크롬, Explorer11)가 비정상종료되는데요..  
혹시 여기에 대한 문제해결 방법이 있나요?  cache refresh방법?

**Comment by easylogic** [comment]
jui-chart 버전이 어떻게 되시나요?

**Comment by easylogic** [comment]
혹시 트랜잭션 데이타 개수가 유지가 되나요? 아님 계속 추가가 되나요?

**Comment by lover74n** [comment]
차트 버전은 작년 12월에 받았는데.. 1점때 버전 아닌가요?
 Transaction View 샘플예제 코드로 테스트했구요.. 똑같은 소스니깐 트랜잭션 데이터가
유지되는거 아닌가요? <-( 근데 작업관리자보면 메모리가 계속 증가되더라구요..)
chart버전 최신버전으로 다시 받아야하나요?

**Comment by lover74n** [comment]
네.. 최신버전으로 해보겠습니다.  감사합니다

**Comment by lover74n** [comment]
최신버전으로 적용하니 문제가 해결되었습니다 감사합니다
