### ISSUE TITLE
JUI Chart 질문 드립니다

### ISSUE THREAD

**Issue by serendijh** [juijs/jui-chart#99]
안녕하세요 바쁘신데 죄송하지만 질문한가지 드립니다.
widget.cross기능을 사용중에
var value = axis.x.invert(e.chartX) 로 값을 변환하는 기능이 있던데
예를들어 y축 도메인 50을 입력하면 차트의 좌표(e.chartX, or e.bgY)로 바꿔주는 기능은 없는건가요?
저 invert의 역기능이 필요합니다..ㅠㅠ
감사합니다.

**Comment by easylogic** [comment]
안녕하세요. 

invert 는 말 그대로 invert  의 기능이구여. 

실제로는 x 가 원래 기능입니다. 

```javascript
var chartY = axis.y(50);  // domain 값을 좌표값으로 변환 해줌. 
```
실제로 좌표 값을 변환해주는 scale 이라 그대로 쓰시면 됩니다.  jui 내부적으로 invert 보다 이게 더 많이 쓰이고 있습니다. 
axis.x() 
axis.y()
